### ISSUE TITLE
This app can't run on your PC

### ISSUE THREAD

**Issue by GitHubKitten** [builtree/handwrite#87]
When trying to run handwrite, after having installed all the required other things, I get the message:

"This app can't run on your PC"

i.e. as a Blue Windows 10 information window.

Since there is no .exe file, I can't set to run in configuration mode.

Please help.

**Comment by yashlamba** [comment]
@GitHubKitten, handwrite is just a CLI tool and isn't packaged as an application. You can't run it as any other application on windows.

**Comment by GitHubKitten** [comment]
Thanks. I am trying to run it from cmd prompt now. But it's not working, I can an error. Here is the cmd prompt messages (please note I am not a developer). Can you see what the error is and how to fix it? To clarify, this is the command I used: "handwrite C:\Users\Name\AppData\Local\Programs\Python\Python311\Scripts\handwrite.jpg C:\Users\Name\AppData\Local\Programs\Python\Python311\Scripts\"

See the full cmd dialogue below:

c:\Users\Name\AppData\Local\Programs\Python\Python311\Scripts>handwrite C:\Users\Name\AppData\Local\Programs\Python\Python311\Scripts\handwrite.jpg C:\Users\Name\AppData\Local\Programs\Python\Python311\Scripts\
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\Name\AppData\Local\Programs\Python\Python311\Scripts\handwrite.exe\__main__.py", line 7, in <module>
  File "C:\Users\Name\AppData\Local\Programs\Python\Python311\Lib\site-packages\handwrite\cli.py", line 56, in main
    converters(
  File "C:\Users\Name\AppData\Local\Programs\Python\Python311\Lib\site-packages\handwrite\cli.py", line 34, in converters
    run(sheet, output_directory, directory, config, metadata)
  File "C:\Users\Name\AppData\Local\Programs\Python\Python311\Lib\site-packages\handwrite\cli.py", line 14, in run
    SVGtoTTF().convert(characters_dir, output_directory, config, metadata)
  File "C:\Users\Name\AppData\Local\Programs\Python\Python311\Lib\site-packages\handwrite\svgtottf.py", line 28, in convert
    subprocess.run(
  File "C:\Users\Name\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Name\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Name\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

c:\Users\Name\AppData\Local\Programs\Python\Python311\Scripts>

**Comment by yashlamba** [comment]
Looks like you don't have [fontforge](https://fontforge.org/en-US/) installed correctly, make sure you enable scripting when installing. If I remember correctly, it comes up as an option when installing.
